#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctaDelivery.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Docta")]
	public partial class DoctaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBarrio(Barrio instance);
    partial void UpdateBarrio(Barrio instance);
    partial void DeleteBarrio(Barrio instance);
    partial void InsertZona(Zona instance);
    partial void UpdateZona(Zona instance);
    partial void DeleteZona(Zona instance);
    partial void InsertComentario(Comentario instance);
    partial void UpdateComentario(Comentario instance);
    partial void DeleteComentario(Comentario instance);
    partial void Insertdelivery(delivery instance);
    partial void Updatedelivery(delivery instance);
    partial void Deletedelivery(delivery instance);
    partial void InsertEstado_pedido(Estado_pedido instance);
    partial void UpdateEstado_pedido(Estado_pedido instance);
    partial void DeleteEstado_pedido(Estado_pedido instance);
    partial void InsertFoto(Foto instance);
    partial void UpdateFoto(Foto instance);
    partial void DeleteFoto(Foto instance);
    partial void InsertNegocio(Negocio instance);
    partial void UpdateNegocio(Negocio instance);
    partial void DeleteNegocio(Negocio instance);
    partial void InsertNegocio_Producto(Negocio_Producto instance);
    partial void UpdateNegocio_Producto(Negocio_Producto instance);
    partial void DeleteNegocio_Producto(Negocio_Producto instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertPublicacion(Publicacion instance);
    partial void UpdatePublicacion(Publicacion instance);
    partial void DeletePublicacion(Publicacion instance);
    partial void InsertTipo_negocio(Tipo_negocio instance);
    partial void UpdateTipo_negocio(Tipo_negocio instance);
    partial void DeleteTipo_negocio(Tipo_negocio instance);
    partial void InsertTipo_producto(Tipo_producto instance);
    partial void UpdateTipo_producto(Tipo_producto instance);
    partial void DeleteTipo_producto(Tipo_producto instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public DoctaDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DoctaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DoctaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoctaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoctaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoctaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Barrio> Barrios
		{
			get
			{
				return this.GetTable<Barrio>();
			}
		}
		
		public System.Data.Linq.Table<Zona> Zonas
		{
			get
			{
				return this.GetTable<Zona>();
			}
		}
		
		public System.Data.Linq.Table<Comentario> Comentarios
		{
			get
			{
				return this.GetTable<Comentario>();
			}
		}
		
		public System.Data.Linq.Table<delivery> deliveries
		{
			get
			{
				return this.GetTable<delivery>();
			}
		}
		
		public System.Data.Linq.Table<Estado_pedido> Estado_pedidos
		{
			get
			{
				return this.GetTable<Estado_pedido>();
			}
		}
		
		public System.Data.Linq.Table<Foto> Fotos
		{
			get
			{
				return this.GetTable<Foto>();
			}
		}
		
		public System.Data.Linq.Table<Negocio> Negocios
		{
			get
			{
				return this.GetTable<Negocio>();
			}
		}
		
		public System.Data.Linq.Table<Negocio_Producto> Negocio_Productos
		{
			get
			{
				return this.GetTable<Negocio_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedidos
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Publicacion> Publicacions
		{
			get
			{
				return this.GetTable<Publicacion>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_negocio> Tipo_negocios
		{
			get
			{
				return this.GetTable<Tipo_negocio>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_producto> Tipo_productos
		{
			get
			{
				return this.GetTable<Tipo_producto>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Barrio")]
	public partial class Barrio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_barrio;
		
		private string _nombre;
		
		private System.Nullable<int> _id_zona;
		
		private EntitySet<Negocio> _Negocios;
		
		private EntitySet<Usuario> _Usuarios;
		
		private EntityRef<Zona> _Zona;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_barrioChanging(int value);
    partial void Onid_barrioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onid_zonaChanging(System.Nullable<int> value);
    partial void Onid_zonaChanged();
    #endregion
		
		public Barrio()
		{
			this._Negocios = new EntitySet<Negocio>(new Action<Negocio>(this.attach_Negocios), new Action<Negocio>(this.detach_Negocios));
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			this._Zona = default(EntityRef<Zona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barrio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_barrio
		{
			get
			{
				return this._id_barrio;
			}
			set
			{
				if ((this._id_barrio != value))
				{
					this.Onid_barrioChanging(value);
					this.SendPropertyChanging();
					this._id_barrio = value;
					this.SendPropertyChanged("id_barrio");
					this.Onid_barrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(35)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zona", DbType="Int")]
		public System.Nullable<int> id_zona
		{
			get
			{
				return this._id_zona;
			}
			set
			{
				if ((this._id_zona != value))
				{
					if (this._Zona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_zonaChanging(value);
					this.SendPropertyChanging();
					this._id_zona = value;
					this.SendPropertyChanged("id_zona");
					this.Onid_zonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barrio_Negocio", Storage="_Negocios", ThisKey="id_barrio", OtherKey="id_barrio")]
		public EntitySet<Negocio> Negocios
		{
			get
			{
				return this._Negocios;
			}
			set
			{
				this._Negocios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barrio_Usuario", Storage="_Usuarios", ThisKey="id_barrio", OtherKey="id_barrio")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zona_Barrio", Storage="_Zona", ThisKey="id_zona", OtherKey="id_zona", IsForeignKey=true)]
		public Zona Zona
		{
			get
			{
				return this._Zona.Entity;
			}
			set
			{
				Zona previousValue = this._Zona.Entity;
				if (((previousValue != value) 
							|| (this._Zona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Zona.Entity = null;
						previousValue.Barrios.Remove(this);
					}
					this._Zona.Entity = value;
					if ((value != null))
					{
						value.Barrios.Add(this);
						this._id_zona = value.id_zona;
					}
					else
					{
						this._id_zona = default(Nullable<int>);
					}
					this.SendPropertyChanged("Zona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Negocios(Negocio entity)
		{
			this.SendPropertyChanging();
			entity.Barrio = this;
		}
		
		private void detach_Negocios(Negocio entity)
		{
			this.SendPropertyChanging();
			entity.Barrio = null;
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Barrio = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Barrio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zona")]
	public partial class Zona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_zona;
		
		private string _zona1;
		
		private EntitySet<Barrio> _Barrios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_zonaChanging(int value);
    partial void Onid_zonaChanged();
    partial void Onzona1Changing(string value);
    partial void Onzona1Changed();
    #endregion
		
		public Zona()
		{
			this._Barrios = new EntitySet<Barrio>(new Action<Barrio>(this.attach_Barrios), new Action<Barrio>(this.detach_Barrios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_zona
		{
			get
			{
				return this._id_zona;
			}
			set
			{
				if ((this._id_zona != value))
				{
					this.Onid_zonaChanging(value);
					this.SendPropertyChanging();
					this._id_zona = value;
					this.SendPropertyChanged("id_zona");
					this.Onid_zonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="zona", Storage="_zona1", DbType="VarChar(40)")]
		public string zona1
		{
			get
			{
				return this._zona1;
			}
			set
			{
				if ((this._zona1 != value))
				{
					this.Onzona1Changing(value);
					this.SendPropertyChanging();
					this._zona1 = value;
					this.SendPropertyChanged("zona1");
					this.Onzona1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zona_Barrio", Storage="_Barrios", ThisKey="id_zona", OtherKey="id_zona")]
		public EntitySet<Barrio> Barrios
		{
			get
			{
				return this._Barrios;
			}
			set
			{
				this._Barrios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Barrios(Barrio entity)
		{
			this.SendPropertyChanging();
			entity.Zona = this;
		}
		
		private void detach_Barrios(Barrio entity)
		{
			this.SendPropertyChanging();
			entity.Zona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentario")]
	public partial class Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_comentario;
		
		private System.Nullable<int> _id_publicacion;
		
		private System.Nullable<int> _id_usuario;
		
		private string _comentario1;
		
		private EntityRef<Publicacion> _Publicacion;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_comentarioChanging(int value);
    partial void Onid_comentarioChanged();
    partial void Onid_publicacionChanging(System.Nullable<int> value);
    partial void Onid_publicacionChanged();
    partial void Onid_usuarioChanging(System.Nullable<int> value);
    partial void Onid_usuarioChanged();
    partial void Oncomentario1Changing(string value);
    partial void Oncomentario1Changed();
    #endregion
		
		public Comentario()
		{
			this._Publicacion = default(EntityRef<Publicacion>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_comentario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_comentario
		{
			get
			{
				return this._id_comentario;
			}
			set
			{
				if ((this._id_comentario != value))
				{
					this.Onid_comentarioChanging(value);
					this.SendPropertyChanging();
					this._id_comentario = value;
					this.SendPropertyChanged("id_comentario");
					this.Onid_comentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", DbType="Int")]
		public System.Nullable<int> id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					if (this._Publicacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_publicacionChanging(value);
					this.SendPropertyChanging();
					this._id_publicacion = value;
					this.SendPropertyChanged("id_publicacion");
					this.Onid_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="comentario", Storage="_comentario1", DbType="VarChar(800)")]
		public string comentario1
		{
			get
			{
				return this._comentario1;
			}
			set
			{
				if ((this._comentario1 != value))
				{
					this.Oncomentario1Changing(value);
					this.SendPropertyChanging();
					this._comentario1 = value;
					this.SendPropertyChanged("comentario1");
					this.Oncomentario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publicacion_Comentario", Storage="_Publicacion", ThisKey="id_publicacion", OtherKey="id_publicacion", IsForeignKey=true)]
		public Publicacion Publicacion
		{
			get
			{
				return this._Publicacion.Entity;
			}
			set
			{
				Publicacion previousValue = this._Publicacion.Entity;
				if (((previousValue != value) 
							|| (this._Publicacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Publicacion.Entity = null;
						previousValue.Comentarios.Remove(this);
					}
					this._Publicacion.Entity = value;
					if ((value != null))
					{
						value.Comentarios.Add(this);
						this._id_publicacion = value.id_publicacion;
					}
					else
					{
						this._id_publicacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Publicacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Comentario", Storage="_Usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Comentarios.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Comentarios.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.delivery")]
	public partial class delivery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_delivery;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _patente;
		
		private string _color_vehiculo;
		
		private System.Nullable<int> _id_negocio;
		
		private EntitySet<Pedido> _Pedidos;
		
		private EntityRef<Negocio> _Negocio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_deliveryChanging(int value);
    partial void Onid_deliveryChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnpatenteChanging(string value);
    partial void OnpatenteChanged();
    partial void Oncolor_vehiculoChanging(string value);
    partial void Oncolor_vehiculoChanged();
    partial void Onid_negocioChanging(System.Nullable<int> value);
    partial void Onid_negocioChanged();
    #endregion
		
		public delivery()
		{
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			this._Negocio = default(EntityRef<Negocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_delivery", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_delivery
		{
			get
			{
				return this._id_delivery;
			}
			set
			{
				if ((this._id_delivery != value))
				{
					this.Onid_deliveryChanging(value);
					this.SendPropertyChanging();
					this._id_delivery = value;
					this.SendPropertyChanged("id_delivery");
					this.Onid_deliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patente", DbType="VarChar(15)")]
		public string patente
		{
			get
			{
				return this._patente;
			}
			set
			{
				if ((this._patente != value))
				{
					this.OnpatenteChanging(value);
					this.SendPropertyChanging();
					this._patente = value;
					this.SendPropertyChanged("patente");
					this.OnpatenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_vehiculo", DbType="VarChar(12)")]
		public string color_vehiculo
		{
			get
			{
				return this._color_vehiculo;
			}
			set
			{
				if ((this._color_vehiculo != value))
				{
					this.Oncolor_vehiculoChanging(value);
					this.SendPropertyChanging();
					this._color_vehiculo = value;
					this.SendPropertyChanged("color_vehiculo");
					this.Oncolor_vehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_negocio", DbType="Int")]
		public System.Nullable<int> id_negocio
		{
			get
			{
				return this._id_negocio;
			}
			set
			{
				if ((this._id_negocio != value))
				{
					if (this._Negocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_negocio = value;
					this.SendPropertyChanged("id_negocio");
					this.Onid_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="delivery_Pedido", Storage="_Pedidos", ThisKey="id_delivery", OtherKey="id_delivery")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_delivery", Storage="_Negocio", ThisKey="id_negocio", OtherKey="id_negocio", IsForeignKey=true)]
		public Negocio Negocio
		{
			get
			{
				return this._Negocio.Entity;
			}
			set
			{
				Negocio previousValue = this._Negocio.Entity;
				if (((previousValue != value) 
							|| (this._Negocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Negocio.Entity = null;
						previousValue.deliveries.Remove(this);
					}
					this._Negocio.Entity = value;
					if ((value != null))
					{
						value.deliveries.Add(this);
						this._id_negocio = value.id_negocio;
					}
					else
					{
						this._id_negocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Negocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.delivery = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.delivery = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_pedido")]
	public partial class Estado_pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_estado_pedido;
		
		private string _nombre;
		
		private EntitySet<Pedido> _Pedidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estado_pedidoChanging(int value);
    partial void Onid_estado_pedidoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Estado_pedido()
		{
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_pedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_estado_pedido
		{
			get
			{
				return this._id_estado_pedido;
			}
			set
			{
				if ((this._id_estado_pedido != value))
				{
					this.Onid_estado_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_estado_pedido = value;
					this.SendPropertyChanged("id_estado_pedido");
					this.Onid_estado_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(15)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_pedido_Pedido", Storage="_Pedidos", ThisKey="id_estado_pedido", OtherKey="id_estado_pedido")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Estado_pedido = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Estado_pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Foto")]
	public partial class Foto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_foto;
		
		private string _nombre;
		
		private System.Nullable<int> _id_publicacion;
		
		private System.Nullable<int> _borrado;
		
		private EntityRef<Publicacion> _Publicacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_fotoChanging(int value);
    partial void Onid_fotoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onid_publicacionChanging(System.Nullable<int> value);
    partial void Onid_publicacionChanged();
    partial void OnborradoChanging(System.Nullable<int> value);
    partial void OnborradoChanged();
    #endregion
		
		public Foto()
		{
			this._Publicacion = default(EntityRef<Publicacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_foto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_foto
		{
			get
			{
				return this._id_foto;
			}
			set
			{
				if ((this._id_foto != value))
				{
					this.Onid_fotoChanging(value);
					this.SendPropertyChanging();
					this._id_foto = value;
					this.SendPropertyChanged("id_foto");
					this.Onid_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(MAX)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", DbType="Int")]
		public System.Nullable<int> id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					if (this._Publicacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_publicacionChanging(value);
					this.SendPropertyChanging();
					this._id_publicacion = value;
					this.SendPropertyChanged("id_publicacion");
					this.Onid_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borrado", DbType="Int")]
		public System.Nullable<int> borrado
		{
			get
			{
				return this._borrado;
			}
			set
			{
				if ((this._borrado != value))
				{
					this.OnborradoChanging(value);
					this.SendPropertyChanging();
					this._borrado = value;
					this.SendPropertyChanged("borrado");
					this.OnborradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publicacion_Foto", Storage="_Publicacion", ThisKey="id_publicacion", OtherKey="id_publicacion", IsForeignKey=true)]
		public Publicacion Publicacion
		{
			get
			{
				return this._Publicacion.Entity;
			}
			set
			{
				Publicacion previousValue = this._Publicacion.Entity;
				if (((previousValue != value) 
							|| (this._Publicacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Publicacion.Entity = null;
						previousValue.Fotos.Remove(this);
					}
					this._Publicacion.Entity = value;
					if ((value != null))
					{
						value.Fotos.Add(this);
						this._id_publicacion = value.id_publicacion;
					}
					else
					{
						this._id_publicacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Publicacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Negocio")]
	public partial class Negocio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_negocio;
		
		private string _nombre;
		
		private System.Nullable<int> _id_barrio;
		
		private System.Nullable<int> _id_tipo_negocio;
		
		private string _calle_numero;
		
		private string _horario_apertura;
		
		private string _horario_cierre;
		
		private System.Nullable<int> _sucursal;
		
		private string _avatar;
		
		private string _contrasenia;
		
		private string _usuario1;
		
		private System.Nullable<int> _telefono;
		
		private EntitySet<delivery> _deliveries;
		
		private EntitySet<Negocio_Producto> _Negocio_Productos;
		
		private EntitySet<Pedido> _Pedidos;
		
		private EntitySet<Producto> _Productos;
		
		private EntitySet<Publicacion> _Publicacions;
		
		private EntityRef<Barrio> _Barrio;
		
		private EntityRef<Tipo_negocio> _Tipo_negocio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_negocioChanging(int value);
    partial void Onid_negocioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onid_barrioChanging(System.Nullable<int> value);
    partial void Onid_barrioChanged();
    partial void Onid_tipo_negocioChanging(System.Nullable<int> value);
    partial void Onid_tipo_negocioChanged();
    partial void Oncalle_numeroChanging(string value);
    partial void Oncalle_numeroChanged();
    partial void Onhorario_aperturaChanging(string value);
    partial void Onhorario_aperturaChanged();
    partial void Onhorario_cierreChanging(string value);
    partial void Onhorario_cierreChanged();
    partial void OnsucursalChanging(System.Nullable<int> value);
    partial void OnsucursalChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OncontraseniaChanging(string value);
    partial void OncontraseniaChanged();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OntelefonoChanging(System.Nullable<int> value);
    partial void OntelefonoChanged();
    #endregion
		
		public Negocio()
		{
			this._deliveries = new EntitySet<delivery>(new Action<delivery>(this.attach_deliveries), new Action<delivery>(this.detach_deliveries));
			this._Negocio_Productos = new EntitySet<Negocio_Producto>(new Action<Negocio_Producto>(this.attach_Negocio_Productos), new Action<Negocio_Producto>(this.detach_Negocio_Productos));
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			this._Publicacions = new EntitySet<Publicacion>(new Action<Publicacion>(this.attach_Publicacions), new Action<Publicacion>(this.detach_Publicacions));
			this._Barrio = default(EntityRef<Barrio>);
			this._Tipo_negocio = default(EntityRef<Tipo_negocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_negocio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_negocio
		{
			get
			{
				return this._id_negocio;
			}
			set
			{
				if ((this._id_negocio != value))
				{
					this.Onid_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_negocio = value;
					this.SendPropertyChanged("id_negocio");
					this.Onid_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barrio", DbType="Int")]
		public System.Nullable<int> id_barrio
		{
			get
			{
				return this._id_barrio;
			}
			set
			{
				if ((this._id_barrio != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_barrioChanging(value);
					this.SendPropertyChanging();
					this._id_barrio = value;
					this.SendPropertyChanged("id_barrio");
					this.Onid_barrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_negocio", DbType="Int")]
		public System.Nullable<int> id_tipo_negocio
		{
			get
			{
				return this._id_tipo_negocio;
			}
			set
			{
				if ((this._id_tipo_negocio != value))
				{
					if (this._Tipo_negocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_negocio = value;
					this.SendPropertyChanged("id_tipo_negocio");
					this.Onid_tipo_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calle_numero", DbType="VarChar(50)")]
		public string calle_numero
		{
			get
			{
				return this._calle_numero;
			}
			set
			{
				if ((this._calle_numero != value))
				{
					this.Oncalle_numeroChanging(value);
					this.SendPropertyChanging();
					this._calle_numero = value;
					this.SendPropertyChanged("calle_numero");
					this.Oncalle_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horario_apertura", DbType="VarChar(10)")]
		public string horario_apertura
		{
			get
			{
				return this._horario_apertura;
			}
			set
			{
				if ((this._horario_apertura != value))
				{
					this.Onhorario_aperturaChanging(value);
					this.SendPropertyChanging();
					this._horario_apertura = value;
					this.SendPropertyChanged("horario_apertura");
					this.Onhorario_aperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horario_cierre", DbType="VarChar(10)")]
		public string horario_cierre
		{
			get
			{
				return this._horario_cierre;
			}
			set
			{
				if ((this._horario_cierre != value))
				{
					this.Onhorario_cierreChanging(value);
					this.SendPropertyChanging();
					this._horario_cierre = value;
					this.SendPropertyChanged("horario_cierre");
					this.Onhorario_cierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sucursal", DbType="Int")]
		public System.Nullable<int> sucursal
		{
			get
			{
				return this._sucursal;
			}
			set
			{
				if ((this._sucursal != value))
				{
					this.OnsucursalChanging(value);
					this.SendPropertyChanging();
					this._sucursal = value;
					this.SendPropertyChanged("sucursal");
					this.OnsucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="VarChar(50)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia", DbType="VarChar(70)")]
		public string contrasenia
		{
			get
			{
				return this._contrasenia;
			}
			set
			{
				if ((this._contrasenia != value))
				{
					this.OncontraseniaChanging(value);
					this.SendPropertyChanging();
					this._contrasenia = value;
					this.SendPropertyChanged("contrasenia");
					this.OncontraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario1", DbType="VarChar(50)")]
		public string usuario1
		{
			get
			{
				return this._usuario1;
			}
			set
			{
				if ((this._usuario1 != value))
				{
					this.Onusuario1Changing(value);
					this.SendPropertyChanging();
					this._usuario1 = value;
					this.SendPropertyChanged("usuario1");
					this.Onusuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_delivery", Storage="_deliveries", ThisKey="id_negocio", OtherKey="id_negocio")]
		public EntitySet<delivery> deliveries
		{
			get
			{
				return this._deliveries;
			}
			set
			{
				this._deliveries.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Negocio_Producto", Storage="_Negocio_Productos", ThisKey="id_negocio", OtherKey="id_negocio")]
		public EntitySet<Negocio_Producto> Negocio_Productos
		{
			get
			{
				return this._Negocio_Productos;
			}
			set
			{
				this._Negocio_Productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Pedido", Storage="_Pedidos", ThisKey="id_negocio", OtherKey="id_negocio")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Producto", Storage="_Productos", ThisKey="id_negocio", OtherKey="id_negocio")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Publicacion", Storage="_Publicacions", ThisKey="id_negocio", OtherKey="id_negocio")]
		public EntitySet<Publicacion> Publicacions
		{
			get
			{
				return this._Publicacions;
			}
			set
			{
				this._Publicacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barrio_Negocio", Storage="_Barrio", ThisKey="id_barrio", OtherKey="id_barrio", IsForeignKey=true)]
		public Barrio Barrio
		{
			get
			{
				return this._Barrio.Entity;
			}
			set
			{
				Barrio previousValue = this._Barrio.Entity;
				if (((previousValue != value) 
							|| (this._Barrio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Barrio.Entity = null;
						previousValue.Negocios.Remove(this);
					}
					this._Barrio.Entity = value;
					if ((value != null))
					{
						value.Negocios.Add(this);
						this._id_barrio = value.id_barrio;
					}
					else
					{
						this._id_barrio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Barrio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_negocio_Negocio", Storage="_Tipo_negocio", ThisKey="id_tipo_negocio", OtherKey="id_tipo_negocio", IsForeignKey=true)]
		public Tipo_negocio Tipo_negocio
		{
			get
			{
				return this._Tipo_negocio.Entity;
			}
			set
			{
				Tipo_negocio previousValue = this._Tipo_negocio.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_negocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_negocio.Entity = null;
						previousValue.Negocios.Remove(this);
					}
					this._Tipo_negocio.Entity = value;
					if ((value != null))
					{
						value.Negocios.Add(this);
						this._id_tipo_negocio = value.id_tipo_negocio;
					}
					else
					{
						this._id_tipo_negocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tipo_negocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_deliveries(delivery entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = this;
		}
		
		private void detach_deliveries(delivery entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = null;
		}
		
		private void attach_Negocio_Productos(Negocio_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = this;
		}
		
		private void detach_Negocio_Productos(Negocio_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = null;
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = null;
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = null;
		}
		
		private void attach_Publicacions(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = this;
		}
		
		private void detach_Publicacions(Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.Negocio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Negocio_Producto")]
	public partial class Negocio_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Negocio_Producto;
		
		private System.Nullable<int> _id_negocio;
		
		private System.Nullable<int> _id_producto;
		
		private EntityRef<Negocio> _Negocio;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_Negocio_ProductoChanging(int value);
    partial void Onid_Negocio_ProductoChanged();
    partial void Onid_negocioChanging(System.Nullable<int> value);
    partial void Onid_negocioChanged();
    partial void Onid_productoChanging(System.Nullable<int> value);
    partial void Onid_productoChanged();
    #endregion
		
		public Negocio_Producto()
		{
			this._Negocio = default(EntityRef<Negocio>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Negocio_Producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Negocio_Producto
		{
			get
			{
				return this._id_Negocio_Producto;
			}
			set
			{
				if ((this._id_Negocio_Producto != value))
				{
					this.Onid_Negocio_ProductoChanging(value);
					this.SendPropertyChanging();
					this._id_Negocio_Producto = value;
					this.SendPropertyChanged("id_Negocio_Producto");
					this.Onid_Negocio_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_negocio", DbType="Int")]
		public System.Nullable<int> id_negocio
		{
			get
			{
				return this._id_negocio;
			}
			set
			{
				if ((this._id_negocio != value))
				{
					if (this._Negocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_negocio = value;
					this.SendPropertyChanged("id_negocio");
					this.Onid_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int")]
		public System.Nullable<int> id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Negocio_Producto", Storage="_Negocio", ThisKey="id_negocio", OtherKey="id_negocio", IsForeignKey=true)]
		public Negocio Negocio
		{
			get
			{
				return this._Negocio.Entity;
			}
			set
			{
				Negocio previousValue = this._Negocio.Entity;
				if (((previousValue != value) 
							|| (this._Negocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Negocio.Entity = null;
						previousValue.Negocio_Productos.Remove(this);
					}
					this._Negocio.Entity = value;
					if ((value != null))
					{
						value.Negocio_Productos.Add(this);
						this._id_negocio = value.id_negocio;
					}
					else
					{
						this._id_negocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Negocio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Negocio_Producto", Storage="_Producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Negocio_Productos.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Negocio_Productos.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pedido;
		
		private string _descripcion;
		
		private System.Nullable<int> _id_usuario;
		
		private System.Nullable<int> _id_negocio;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<int> _id_delivery;
		
		private System.Nullable<int> _id_estado_pedido;
		
		private System.Nullable<int> _id_tipo_producto;
		
		private EntityRef<delivery> _delivery;
		
		private EntityRef<Estado_pedido> _Estado_pedido;
		
		private EntityRef<Negocio> _Negocio;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pedidoChanging(int value);
    partial void Onid_pedidoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onid_usuarioChanging(System.Nullable<int> value);
    partial void Onid_usuarioChanged();
    partial void Onid_negocioChanging(System.Nullable<int> value);
    partial void Onid_negocioChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void Onid_deliveryChanging(System.Nullable<int> value);
    partial void Onid_deliveryChanged();
    partial void Onid_estado_pedidoChanging(System.Nullable<int> value);
    partial void Onid_estado_pedidoChanged();
    partial void Onid_tipo_productoChanging(System.Nullable<int> value);
    partial void Onid_tipo_productoChanged();
    #endregion
		
		public Pedido()
		{
			this._delivery = default(EntityRef<delivery>);
			this._Estado_pedido = default(EntityRef<Estado_pedido>);
			this._Negocio = default(EntityRef<Negocio>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pedido
		{
			get
			{
				return this._id_pedido;
			}
			set
			{
				if ((this._id_pedido != value))
				{
					this.Onid_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_pedido = value;
					this.SendPropertyChanged("id_pedido");
					this.Onid_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(300)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int")]
		public System.Nullable<int> id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_negocio", DbType="Int")]
		public System.Nullable<int> id_negocio
		{
			get
			{
				return this._id_negocio;
			}
			set
			{
				if ((this._id_negocio != value))
				{
					if (this._Negocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_negocio = value;
					this.SendPropertyChanged("id_negocio");
					this.Onid_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_delivery", DbType="Int")]
		public System.Nullable<int> id_delivery
		{
			get
			{
				return this._id_delivery;
			}
			set
			{
				if ((this._id_delivery != value))
				{
					if (this._delivery.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_deliveryChanging(value);
					this.SendPropertyChanging();
					this._id_delivery = value;
					this.SendPropertyChanged("id_delivery");
					this.Onid_deliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado_pedido", DbType="Int")]
		public System.Nullable<int> id_estado_pedido
		{
			get
			{
				return this._id_estado_pedido;
			}
			set
			{
				if ((this._id_estado_pedido != value))
				{
					if (this._Estado_pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estado_pedidoChanging(value);
					this.SendPropertyChanging();
					this._id_estado_pedido = value;
					this.SendPropertyChanged("id_estado_pedido");
					this.Onid_estado_pedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_producto", DbType="Int")]
		public System.Nullable<int> id_tipo_producto
		{
			get
			{
				return this._id_tipo_producto;
			}
			set
			{
				if ((this._id_tipo_producto != value))
				{
					this.Onid_tipo_productoChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_producto = value;
					this.SendPropertyChanged("id_tipo_producto");
					this.Onid_tipo_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="delivery_Pedido", Storage="_delivery", ThisKey="id_delivery", OtherKey="id_delivery", IsForeignKey=true)]
		public delivery delivery
		{
			get
			{
				return this._delivery.Entity;
			}
			set
			{
				delivery previousValue = this._delivery.Entity;
				if (((previousValue != value) 
							|| (this._delivery.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._delivery.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._delivery.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._id_delivery = value.id_delivery;
					}
					else
					{
						this._id_delivery = default(Nullable<int>);
					}
					this.SendPropertyChanged("delivery");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_pedido_Pedido", Storage="_Estado_pedido", ThisKey="id_estado_pedido", OtherKey="id_estado_pedido", IsForeignKey=true)]
		public Estado_pedido Estado_pedido
		{
			get
			{
				return this._Estado_pedido.Entity;
			}
			set
			{
				Estado_pedido previousValue = this._Estado_pedido.Entity;
				if (((previousValue != value) 
							|| (this._Estado_pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado_pedido.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Estado_pedido.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._id_estado_pedido = value.id_estado_pedido;
					}
					else
					{
						this._id_estado_pedido = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado_pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Pedido", Storage="_Negocio", ThisKey="id_negocio", OtherKey="id_negocio", IsForeignKey=true)]
		public Negocio Negocio
		{
			get
			{
				return this._Negocio.Entity;
			}
			set
			{
				Negocio previousValue = this._Negocio.Entity;
				if (((previousValue != value) 
							|| (this._Negocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Negocio.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Negocio.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._id_negocio = value.id_negocio;
					}
					else
					{
						this._id_negocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Negocio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Pedido", Storage="_Usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _tiempo;
		
		private System.Nullable<int> _coins;
		
		private System.Nullable<int> _id_tipo_producto;
		
		private System.Nullable<int> _id_negocio;
		
		private System.Nullable<int> _borrado;
		
		private EntitySet<Negocio_Producto> _Negocio_Productos;
		
		private EntityRef<Negocio> _Negocio;
		
		private EntityRef<Tipo_producto> _Tipo_producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OntiempoChanging(System.Nullable<int> value);
    partial void OntiempoChanged();
    partial void OncoinsChanging(System.Nullable<int> value);
    partial void OncoinsChanged();
    partial void Onid_tipo_productoChanging(System.Nullable<int> value);
    partial void Onid_tipo_productoChanged();
    partial void Onid_negocioChanging(System.Nullable<int> value);
    partial void Onid_negocioChanged();
    partial void OnborradoChanging(System.Nullable<int> value);
    partial void OnborradoChanged();
    #endregion
		
		public Producto()
		{
			this._Negocio_Productos = new EntitySet<Negocio_Producto>(new Action<Negocio_Producto>(this.attach_Negocio_Productos), new Action<Negocio_Producto>(this.detach_Negocio_Productos));
			this._Negocio = default(EntityRef<Negocio>);
			this._Tipo_producto = default(EntityRef<Tipo_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(400)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo", DbType="Int")]
		public System.Nullable<int> tiempo
		{
			get
			{
				return this._tiempo;
			}
			set
			{
				if ((this._tiempo != value))
				{
					this.OntiempoChanging(value);
					this.SendPropertyChanging();
					this._tiempo = value;
					this.SendPropertyChanged("tiempo");
					this.OntiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coins", DbType="Int")]
		public System.Nullable<int> coins
		{
			get
			{
				return this._coins;
			}
			set
			{
				if ((this._coins != value))
				{
					this.OncoinsChanging(value);
					this.SendPropertyChanging();
					this._coins = value;
					this.SendPropertyChanged("coins");
					this.OncoinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_producto", DbType="Int")]
		public System.Nullable<int> id_tipo_producto
		{
			get
			{
				return this._id_tipo_producto;
			}
			set
			{
				if ((this._id_tipo_producto != value))
				{
					if (this._Tipo_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_productoChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_producto = value;
					this.SendPropertyChanged("id_tipo_producto");
					this.Onid_tipo_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_negocio", DbType="Int")]
		public System.Nullable<int> id_negocio
		{
			get
			{
				return this._id_negocio;
			}
			set
			{
				if ((this._id_negocio != value))
				{
					if (this._Negocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_negocio = value;
					this.SendPropertyChanged("id_negocio");
					this.Onid_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borrado", DbType="Int")]
		public System.Nullable<int> borrado
		{
			get
			{
				return this._borrado;
			}
			set
			{
				if ((this._borrado != value))
				{
					this.OnborradoChanging(value);
					this.SendPropertyChanging();
					this._borrado = value;
					this.SendPropertyChanged("borrado");
					this.OnborradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Negocio_Producto", Storage="_Negocio_Productos", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<Negocio_Producto> Negocio_Productos
		{
			get
			{
				return this._Negocio_Productos;
			}
			set
			{
				this._Negocio_Productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Producto", Storage="_Negocio", ThisKey="id_negocio", OtherKey="id_negocio", IsForeignKey=true)]
		public Negocio Negocio
		{
			get
			{
				return this._Negocio.Entity;
			}
			set
			{
				Negocio previousValue = this._Negocio.Entity;
				if (((previousValue != value) 
							|| (this._Negocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Negocio.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Negocio.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._id_negocio = value.id_negocio;
					}
					else
					{
						this._id_negocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Negocio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_producto_Producto", Storage="_Tipo_producto", ThisKey="id_tipo_producto", OtherKey="id_tipo_producto", IsForeignKey=true)]
		public Tipo_producto Tipo_producto
		{
			get
			{
				return this._Tipo_producto.Entity;
			}
			set
			{
				Tipo_producto previousValue = this._Tipo_producto.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_producto.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Tipo_producto.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._id_tipo_producto = value.id_tipo_producto;
					}
					else
					{
						this._id_tipo_producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tipo_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Negocio_Productos(Negocio_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Negocio_Productos(Negocio_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Publicacion")]
	public partial class Publicacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_publicacion;
		
		private System.Nullable<int> _id_negocio;
		
		private string _valoracion;
		
		private string _descripcion;
		
		private string _titulo;
		
		private EntitySet<Comentario> _Comentarios;
		
		private EntitySet<Foto> _Fotos;
		
		private EntityRef<Negocio> _Negocio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_publicacionChanging(int value);
    partial void Onid_publicacionChanged();
    partial void Onid_negocioChanging(System.Nullable<int> value);
    partial void Onid_negocioChanged();
    partial void OnvaloracionChanging(string value);
    partial void OnvaloracionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    #endregion
		
		public Publicacion()
		{
			this._Comentarios = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentarios), new Action<Comentario>(this.detach_Comentarios));
			this._Fotos = new EntitySet<Foto>(new Action<Foto>(this.attach_Fotos), new Action<Foto>(this.detach_Fotos));
			this._Negocio = default(EntityRef<Negocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_publicacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_publicacion
		{
			get
			{
				return this._id_publicacion;
			}
			set
			{
				if ((this._id_publicacion != value))
				{
					this.Onid_publicacionChanging(value);
					this.SendPropertyChanging();
					this._id_publicacion = value;
					this.SendPropertyChanged("id_publicacion");
					this.Onid_publicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_negocio", DbType="Int")]
		public System.Nullable<int> id_negocio
		{
			get
			{
				return this._id_negocio;
			}
			set
			{
				if ((this._id_negocio != value))
				{
					if (this._Negocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_negocio = value;
					this.SendPropertyChanged("id_negocio");
					this.Onid_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoracion", DbType="VarChar(500)")]
		public string valoracion
		{
			get
			{
				return this._valoracion;
			}
			set
			{
				if ((this._valoracion != value))
				{
					this.OnvaloracionChanging(value);
					this.SendPropertyChanging();
					this._valoracion = value;
					this.SendPropertyChanged("valoracion");
					this.OnvaloracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(900)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(50)")]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publicacion_Comentario", Storage="_Comentarios", ThisKey="id_publicacion", OtherKey="id_publicacion")]
		public EntitySet<Comentario> Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				this._Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publicacion_Foto", Storage="_Fotos", ThisKey="id_publicacion", OtherKey="id_publicacion")]
		public EntitySet<Foto> Fotos
		{
			get
			{
				return this._Fotos;
			}
			set
			{
				this._Fotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Negocio_Publicacion", Storage="_Negocio", ThisKey="id_negocio", OtherKey="id_negocio", IsForeignKey=true)]
		public Negocio Negocio
		{
			get
			{
				return this._Negocio.Entity;
			}
			set
			{
				Negocio previousValue = this._Negocio.Entity;
				if (((previousValue != value) 
							|| (this._Negocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Negocio.Entity = null;
						previousValue.Publicacions.Remove(this);
					}
					this._Negocio.Entity = value;
					if ((value != null))
					{
						value.Publicacions.Add(this);
						this._id_negocio = value.id_negocio;
					}
					else
					{
						this._id_negocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Negocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Publicacion = this;
		}
		
		private void detach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Publicacion = null;
		}
		
		private void attach_Fotos(Foto entity)
		{
			this.SendPropertyChanging();
			entity.Publicacion = this;
		}
		
		private void detach_Fotos(Foto entity)
		{
			this.SendPropertyChanging();
			entity.Publicacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_negocio")]
	public partial class Tipo_negocio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipo_negocio;
		
		private string _tipo;
		
		private EntitySet<Negocio> _Negocios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_negocioChanging(int value);
    partial void Onid_tipo_negocioChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public Tipo_negocio()
		{
			this._Negocios = new EntitySet<Negocio>(new Action<Negocio>(this.attach_Negocios), new Action<Negocio>(this.detach_Negocios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_negocio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipo_negocio
		{
			get
			{
				return this._id_tipo_negocio;
			}
			set
			{
				if ((this._id_tipo_negocio != value))
				{
					this.Onid_tipo_negocioChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_negocio = value;
					this.SendPropertyChanged("id_tipo_negocio");
					this.Onid_tipo_negocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(25)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_negocio_Negocio", Storage="_Negocios", ThisKey="id_tipo_negocio", OtherKey="id_tipo_negocio")]
		public EntitySet<Negocio> Negocios
		{
			get
			{
				return this._Negocios;
			}
			set
			{
				this._Negocios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Negocios(Negocio entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_negocio = this;
		}
		
		private void detach_Negocios(Negocio entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_negocio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_producto")]
	public partial class Tipo_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipo_producto;
		
		private string _nombre;
		
		private EntitySet<Producto> _Productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_productoChanging(int value);
    partial void Onid_tipo_productoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Tipo_producto()
		{
			this._Productos = new EntitySet<Producto>(new Action<Producto>(this.attach_Productos), new Action<Producto>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipo_producto
		{
			get
			{
				return this._id_tipo_producto;
			}
			set
			{
				if ((this._id_tipo_producto != value))
				{
					this.Onid_tipo_productoChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_producto = value;
					this.SendPropertyChanged("id_tipo_producto");
					this.Onid_tipo_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_producto_Producto", Storage="_Productos", ThisKey="id_tipo_producto", OtherKey="id_tipo_producto")]
		public EntitySet<Producto> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_producto = this;
		}
		
		private void detach_Productos(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nombre;
		
		private string _apellido;
		
		private System.Nullable<int> _telefono;
		
		private System.Nullable<int> _id_barrio;
		
		private string _calle_numero;
		
		private System.Nullable<System.DateTime> _fecha_nac;
		
		private string _e_mail;
		
		private System.Nullable<int> _coins;
		
		private string _contrasenia;
		
		private string _avatar;
		
		private string _usuario1;
		
		private string _documento;
		
		private EntitySet<Comentario> _Comentarios;
		
		private EntitySet<Pedido> _Pedidos;
		
		private EntityRef<Barrio> _Barrio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OntelefonoChanging(System.Nullable<int> value);
    partial void OntelefonoChanged();
    partial void Onid_barrioChanging(System.Nullable<int> value);
    partial void Onid_barrioChanged();
    partial void Oncalle_numeroChanging(string value);
    partial void Oncalle_numeroChanged();
    partial void Onfecha_nacChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacChanged();
    partial void One_mailChanging(string value);
    partial void One_mailChanged();
    partial void OncoinsChanging(System.Nullable<int> value);
    partial void OncoinsChanged();
    partial void OncontraseniaChanging(string value);
    partial void OncontraseniaChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OndocumentoChanging(string value);
    partial void OndocumentoChanged();
    #endregion
		
		public Usuario()
		{
			this._Comentarios = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentarios), new Action<Comentario>(this.detach_Comentarios));
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			this._Barrio = default(EntityRef<Barrio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barrio", DbType="Int")]
		public System.Nullable<int> id_barrio
		{
			get
			{
				return this._id_barrio;
			}
			set
			{
				if ((this._id_barrio != value))
				{
					if (this._Barrio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_barrioChanging(value);
					this.SendPropertyChanging();
					this._id_barrio = value;
					this.SendPropertyChanged("id_barrio");
					this.Onid_barrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calle_numero", DbType="VarChar(80)")]
		public string calle_numero
		{
			get
			{
				return this._calle_numero;
			}
			set
			{
				if ((this._calle_numero != value))
				{
					this.Oncalle_numeroChanging(value);
					this.SendPropertyChanging();
					this._calle_numero = value;
					this.SendPropertyChanged("calle_numero");
					this.Oncalle_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fecha_nac
		{
			get
			{
				return this._fecha_nac;
			}
			set
			{
				if ((this._fecha_nac != value))
				{
					this.Onfecha_nacChanging(value);
					this.SendPropertyChanging();
					this._fecha_nac = value;
					this.SendPropertyChanged("fecha_nac");
					this.Onfecha_nacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="VarChar(80)")]
		public string e_mail
		{
			get
			{
				return this._e_mail;
			}
			set
			{
				if ((this._e_mail != value))
				{
					this.One_mailChanging(value);
					this.SendPropertyChanging();
					this._e_mail = value;
					this.SendPropertyChanged("e_mail");
					this.One_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coins", DbType="Int")]
		public System.Nullable<int> coins
		{
			get
			{
				return this._coins;
			}
			set
			{
				if ((this._coins != value))
				{
					this.OncoinsChanging(value);
					this.SendPropertyChanging();
					this._coins = value;
					this.SendPropertyChanged("coins");
					this.OncoinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia", DbType="VarChar(70)")]
		public string contrasenia
		{
			get
			{
				return this._contrasenia;
			}
			set
			{
				if ((this._contrasenia != value))
				{
					this.OncontraseniaChanging(value);
					this.SendPropertyChanging();
					this._contrasenia = value;
					this.SendPropertyChanged("contrasenia");
					this.OncontraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="VarChar(60)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_usuario1", DbType="VarChar(50)")]
		public string usuario1
		{
			get
			{
				return this._usuario1;
			}
			set
			{
				if ((this._usuario1 != value))
				{
					this.Onusuario1Changing(value);
					this.SendPropertyChanging();
					this._usuario1 = value;
					this.SendPropertyChanged("usuario1");
					this.Onusuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="VarChar(8)")]
		public string documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this.OndocumentoChanging(value);
					this.SendPropertyChanging();
					this._documento = value;
					this.SendPropertyChanged("documento");
					this.OndocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Comentario", Storage="_Comentarios", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<Comentario> Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				this._Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Pedido", Storage="_Pedidos", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Barrio_Usuario", Storage="_Barrio", ThisKey="id_barrio", OtherKey="id_barrio", IsForeignKey=true)]
		public Barrio Barrio
		{
			get
			{
				return this._Barrio.Entity;
			}
			set
			{
				Barrio previousValue = this._Barrio.Entity;
				if (((previousValue != value) 
							|| (this._Barrio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Barrio.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Barrio.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._id_barrio = value.id_barrio;
					}
					else
					{
						this._id_barrio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Barrio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
}
#pragma warning restore 1591
